[project]
name = "week1-initial-setup-liamdormon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pytest>=9.0.2",
]
